#!/usr/bin/env python3
# Requires: pip install rwa-shared  (which installs httpx)
"""Reproducible search script generated by the Research Workflow Assistant.

Source  : openalex
Query   : community health worker maternal mental health low-income countries
Created : 2026-03-15T11:58:17.647788+00:00
Params  : {"filters": null, "sort": "relevance_score:desc", "per_page": 20}
"""

from pathlib import Path

from rwa_result_store.search_runners import run_openalex

PROJECT_PATH = str(Path(__file__).resolve().parent.parent)
search_id = run_openalex(
    project_path=PROJECT_PATH,
    query="community health worker maternal mental health low-income countries",
    filters=None,
    sort="relevance_score:desc",
    per_page=20,
)
print(search_id if search_id else "NO_RESULTS")
