#!/usr/bin/env python3
# Requires: pip install rwa-shared  (which installs httpx)
"""Reproducible search script generated by the Research Workflow Assistant.

Source  : europe_pmc
Query   : community health worker maternal mental health low-income countries
Created : 2026-03-15T11:58:21.861543+00:00
Params  : {"result_type": "core", "page_size": 25, "sort": "relevance", "open_access_only": false}
"""

from pathlib import Path

from rwa_result_store.search_runners import run_europe_pmc

PROJECT_PATH = str(Path(__file__).resolve().parent.parent)
search_id = run_europe_pmc(
    project_path=PROJECT_PATH,
    query="community health worker maternal mental health low-income countries",
    result_type="core",
    page_size=25,
    sort="relevance",
    open_access_only=False,
)
print(search_id if search_id else "NO_RESULTS")
