#!/usr/bin/env python3
# Requires: pip install rwa-shared  (which installs httpx)
"""Reproducible search script generated by the Research Workflow Assistant.

Source  : pubmed
Query   : community health worker maternal mental health low-income countries
Created : 2026-03-15T11:58:05.698677+00:00
Params  : {"max_results": 20, "date_range": null, "article_types": null}
"""
from pathlib import Path

from rwa_result_store.search_runners import run_pubmed

PROJECT_PATH = str(Path(__file__).resolve().parent.parent)
search_id = run_pubmed(
    project_path=PROJECT_PATH,
    query='community health worker maternal mental health low-income countries',
    max_results=20,
    date_range=None,
    article_types=None,
)
print(search_id if search_id else "NO_RESULTS")
