<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="No Author">
<meta name="dcterms.date" content="2026-03-14">

<title>Effectiveness of Community Health Worker Interventions for Maternal Mental Health in Low- and Middle-Income Countries: A Systematic Review</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="manuscript_files/libs/clipboard/clipboard.min.js"></script>
<script src="manuscript_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="manuscript_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="manuscript_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="manuscript_files/libs/quarto-html/popper.min.js"></script>
<script src="manuscript_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="manuscript_files/libs/quarto-html/anchor.min.js"></script>
<link href="manuscript_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="manuscript_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="manuscript_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="manuscript_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="manuscript_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">2</span> Methods</a>
  <ul class="collapse">
  <li><a href="#eligibility-criteria" id="toc-eligibility-criteria" class="nav-link" data-scroll-target="#eligibility-criteria"><span class="header-section-number">2.1</span> Eligibility Criteria</a></li>
  <li><a href="#information-sources-and-search-strategy" id="toc-information-sources-and-search-strategy" class="nav-link" data-scroll-target="#information-sources-and-search-strategy"><span class="header-section-number">2.2</span> Information Sources and Search Strategy</a></li>
  <li><a href="#study-selection" id="toc-study-selection" class="nav-link" data-scroll-target="#study-selection"><span class="header-section-number">2.3</span> Study Selection</a></li>
  <li><a href="#data-extraction" id="toc-data-extraction" class="nav-link" data-scroll-target="#data-extraction"><span class="header-section-number">2.4</span> Data Extraction</a></li>
  <li><a href="#risk-of-bias-assessment" id="toc-risk-of-bias-assessment" class="nav-link" data-scroll-target="#risk-of-bias-assessment"><span class="header-section-number">2.5</span> Risk of Bias Assessment</a></li>
  <li><a href="#data-synthesis" id="toc-data-synthesis" class="nav-link" data-scroll-target="#data-synthesis"><span class="header-section-number">2.6</span> Data Synthesis</a></li>
  <li><a href="#use-of-research-workflow-assistant-rwa" id="toc-use-of-research-workflow-assistant-rwa" class="nav-link" data-scroll-target="#use-of-research-workflow-assistant-rwa"><span class="header-section-number">2.7</span> Use of Research Workflow Assistant (RWA)</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">3</span> Results</a>
  <ul class="collapse">
  <li><a href="#study-selection-1" id="toc-study-selection-1" class="nav-link" data-scroll-target="#study-selection-1"><span class="header-section-number">3.1</span> Study Selection</a></li>
  <li><a href="#study-characteristics" id="toc-study-characteristics" class="nav-link" data-scroll-target="#study-characteristics"><span class="header-section-number">3.2</span> Study Characteristics</a></li>
  <li><a href="#interventions" id="toc-interventions" class="nav-link" data-scroll-target="#interventions"><span class="header-section-number">3.3</span> Interventions</a></li>
  <li><a href="#outcome-measures" id="toc-outcome-measures" class="nav-link" data-scroll-target="#outcome-measures"><span class="header-section-number">3.4</span> Outcome Measures</a></li>
  <li><a href="#effectiveness" id="toc-effectiveness" class="nav-link" data-scroll-target="#effectiveness"><span class="header-section-number">3.5</span> Effectiveness</a>
  <ul class="collapse">
  <li><a href="#studies-reporting-significant-benefits" id="toc-studies-reporting-significant-benefits" class="nav-link" data-scroll-target="#studies-reporting-significant-benefits"><span class="header-section-number">3.5.1</span> Studies Reporting Significant Benefits</a></li>
  <li><a href="#studies-reporting-null-or-transient-effects" id="toc-studies-reporting-null-or-transient-effects" class="nav-link" data-scroll-target="#studies-reporting-null-or-transient-effects"><span class="header-section-number">3.5.2</span> Studies Reporting Null or Transient Effects</a></li>
  </ul></li>
  <li><a href="#risk-of-bias" id="toc-risk-of-bias" class="nav-link" data-scroll-target="#risk-of-bias"><span class="header-section-number">3.6</span> Risk of Bias</a></li>
  <li><a href="#meta-analysis-feasibility" id="toc-meta-analysis-feasibility" class="nav-link" data-scroll-target="#meta-analysis-feasibility"><span class="header-section-number">3.7</span> Meta-Analysis Feasibility</a></li>
  <li><a href="#certainty-of-evidence-grade" id="toc-certainty-of-evidence-grade" class="nav-link" data-scroll-target="#certainty-of-evidence-grade"><span class="header-section-number">3.8</span> Certainty of Evidence (GRADE)</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">4</span> Discussion</a>
  <ul class="collapse">
  <li><a href="#summary-of-evidence" id="toc-summary-of-evidence" class="nav-link" data-scroll-target="#summary-of-evidence"><span class="header-section-number">4.1</span> Summary of Evidence</a></li>
  <li><a href="#patterns-in-effectiveness" id="toc-patterns-in-effectiveness" class="nav-link" data-scroll-target="#patterns-in-effectiveness"><span class="header-section-number">4.2</span> Patterns in Effectiveness</a></li>
  <li><a href="#strengths-and-limitations" id="toc-strengths-and-limitations" class="nav-link" data-scroll-target="#strengths-and-limitations"><span class="header-section-number">4.3</span> Strengths and Limitations</a></li>
  <li><a href="#comparison-with-previous-reviews" id="toc-comparison-with-previous-reviews" class="nav-link" data-scroll-target="#comparison-with-previous-reviews"><span class="header-section-number">4.4</span> Comparison with Previous Reviews</a></li>
  <li><a href="#implications-for-practice" id="toc-implications-for-practice" class="nav-link" data-scroll-target="#implications-for-practice"><span class="header-section-number">4.5</span> Implications for Practice</a></li>
  <li><a href="#implications-for-research" id="toc-implications-for-research" class="nav-link" data-scroll-target="#implications-for-research"><span class="header-section-number">4.6</span> Implications for Research</a></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">5</span> Conclusions</a></li>
  <li><a href="#acknowledgments-and-ai-disclosure" id="toc-acknowledgments-and-ai-disclosure" class="nav-link" data-scroll-target="#acknowledgments-and-ai-disclosure">Acknowledgments and AI Disclosure</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="manuscript.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="..\..\manuscript.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Effectiveness of Community Health Worker Interventions for Maternal Mental Health in Low- and Middle-Income Countries: A Systematic Review</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>No Author </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 14, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p><strong>Background:</strong> Maternal depression and anxiety during the perinatal period affect an estimated 15–25% of women in low- and middle-income countries (LMICs), yet access to professional mental health services remains severely limited. Task-shifting interventions to community health workers (CHWs) has emerged as a strategy to address this treatment gap.</p>
    <p><strong>Objective:</strong> To systematically review evidence on the effectiveness of CHW-delivered psychosocial and psychological interventions in reducing symptoms of depression and anxiety among perinatal women in LMICs.</p>
    <p><strong>Methods:</strong> Five electronic databases (PubMed, OpenAlex, Semantic Scholar, Europe PMC, CrossRef) were searched from inception through March 2026. Eligible studies were randomized controlled trials evaluating CHW-delivered mental health interventions for perinatal women in LMICs, with depression or anxiety measured by validated scales. Risk of bias was assessed using the Cochrane RoB 2 tool. Evidence certainty was evaluated using the GRADE framework. PRISMA 2020 guidelines were followed.</p>
    <p><strong>Results:</strong> Seven RCTs (five cluster-RCTs, one individual RCT, one pilot RCT) involving approximately 4,274 randomized participants from six countries met inclusion criteria. Three studies in lower-middle-income countries reported significant reductions in depression symptoms (effect sizes ranging from small [Cohen’s d = −0.20] to very large [mean difference = −7.2 EPDS points]). All four studies in upper-middle-income countries reported null or transient effects. Six different outcome scales precluded meta-analysis. Risk of bias ranged from low (1 study) to high (1 study), with 5 at some concerns. Notably, the lowest-risk-of-bias study (double-blind, clinician-rated) found null results. GRADE certainty was rated very low.</p>
    <p><strong>Conclusions:</strong> CHW-delivered interventions may reduce maternal depression symptoms in lower-middle-income settings, particularly when integrated with parenting or nutrition programs and targeted to clinically depressed women. However, evidence certainty is very low due to heterogeneity in interventions, outcome measures, and study quality. Standardized outcome reporting and high-quality trials in low-income countries are needed.</p>
    <p><strong>Registration:</strong> Not registered.</p>
  </div>
</div>


</header>


<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Sample Project Disclaimer
</div>
</div>
<div class="callout-body-container callout-body">
<p>This manuscript is a <strong>sample project</strong> created to demonstrate the current functionality of the Research Workflow Assistant (RWA). It is <strong>not</strong> a model of how the tool is intended to be used in practice. No author claims authorship of this work. None of the content has been independently verified and may contain errors, inaccuracies, or incomplete information. This document should not be cited, used for clinical decision-making, or treated as a valid systematic review.</p>
</div>
</div>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Maternal mental health disorders during the perinatal period — encompassing pregnancy through the first year postpartum — represent a significant and growing global health concern. Depression and anxiety are the most common perinatal mental health conditions, with prevalence estimates in low- and middle-income countries (LMICs) consistently exceeding those in high-income settings. Pooled estimates suggest that 15–25% of perinatal women in LMICs experience clinically significant depressive symptoms, with some studies reporting rates above 30% in resource-limited communities <span class="citation" data-cites="fisher2012 woody2017">(<a href="#ref-fisher2012" role="doc-biblioref">Fisher et al., 2012</a>; <a href="#ref-woody2017" role="doc-biblioref">Woody et al., 2017</a>)</span>. These disorders are associated with adverse outcomes for mothers (impaired functioning, reduced quality of life, increased suicidality), infants (low birth weight, impaired cognitive and socio-emotional development), and families (disrupted caregiving, economic consequences) <span class="citation" data-cites="surkan2011 stein2014">(<a href="#ref-stein2014" role="doc-biblioref">Stein et al., 2014</a>; <a href="#ref-surkan2011" role="doc-biblioref">Surkan et al., 2011</a>)</span>.</p>
<p>Despite this burden, the vast majority of affected women in LMICs receive no treatment. A critical shortage of mental health professionals — fewer than 1 psychiatrist per 100,000 population in many low-income countries — combined with stigma, cost, and geographic barriers makes conventional mental health care inaccessible for most perinatal women <span class="citation" data-cites="who2021atlas">(<a href="#ref-who2021atlas" role="doc-biblioref">World Health Organization, 2021</a>)</span>. Task-shifting, defined as the delegation of clinical tasks from specialist providers to less specialized health workers, has been widely advocated as a strategy to address this gap <span class="citation" data-cites="who2008taskshifting">(<a href="#ref-who2008taskshifting" role="doc-biblioref">World Health Organization, 2008</a>)</span>. Community health workers (CHWs), lay health workers, and peer counselors — who live in and are trusted by the communities they serve — are well positioned to deliver basic psychosocial and psychological interventions in routine perinatal care settings.</p>
<p>A growing body of evidence from individual randomized controlled trials (RCTs) has evaluated CHW-delivered interventions targeting perinatal depression and anxiety in LMICs. These interventions range from structured cognitive-behavioral therapy (CBT) adaptations such as the WHO Thinking Healthy Programme <span class="citation" data-cites="rahman2008">(<a href="#ref-rahman2008" role="doc-biblioref">Rahman et al., 2008</a>)</span> to integrated parenting and mental health programs, psychoeducation, and psychosocial home visiting. However, the evidence base is characterized by substantial heterogeneity in intervention type, outcome measurement, population characteristics, and study quality.</p>
<p>This systematic review aimed to (1) synthesize evidence on the effectiveness of CHW-delivered psychosocial and psychological interventions for reducing symptoms of maternal depression and anxiety in LMICs, (2) describe the types of interventions, training models, and delivery formats used, (3) identify patterns in effectiveness by intervention type, setting, and population characteristics, and (4) assess the quality and certainty of the available evidence.</p>
</section>
<section id="methods" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Methods</h1>
<p>This systematic review was conducted in accordance with the Preferred Reporting Items for Systematic Reviews and Meta-Analyses (PRISMA) 2020 guidelines <span class="citation" data-cites="page2021prisma">(<a href="#ref-page2021prisma" role="doc-biblioref">Page et al., 2021</a>)</span>. The protocol was developed a priori but was not registered in a public registry.</p>
<section id="eligibility-criteria" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="eligibility-criteria"><span class="header-section-number">2.1</span> Eligibility Criteria</h2>
<p>Studies were eligible if they met all of the following criteria: (1) population — pregnant women or women up to 12 months postpartum in LMICs as classified by the World Bank at the time of the study; (2) intervention — any psychosocial or psychological intervention delivered primarily by CHWs, lay health workers, or peer counselors; (3) comparator — usual care, enhanced usual care, active control, or no intervention; (4) outcome — at least one validated measure of maternal depression or anxiety symptoms; and (5) design — randomized controlled trial or cluster-randomized trial published in a peer-reviewed journal.</p>
<p>Studies were excluded if interventions were delivered exclusively by professional mental health providers without CHW involvement, if CHWs performed only screening or referral without a therapeutic component, or if the study was conducted exclusively in a high-income country.</p>
</section>
<section id="information-sources-and-search-strategy" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="information-sources-and-search-strategy"><span class="header-section-number">2.2</span> Information Sources and Search Strategy</h2>
<p>Five electronic databases were searched from inception through March 14, 2026: PubMed/MEDLINE (via NCBI), OpenAlex (via API), Semantic Scholar (via API), Europe PMC (via EBI), and CrossRef (via API). A Boolean search strategy was developed using a combination of MeSH terms and free-text synonyms across four concept blocks: population (perinatal women), intervention (community health workers), outcome (depression/anxiety), and setting (LMICs). The complete search strategy is available in the review protocol.</p>
</section>
<section id="study-selection" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="study-selection"><span class="header-section-number">2.3</span> Study Selection</h2>
<p>Records were deduplicated by DOI and PMID matching. Title and abstract screening was performed by a single user with AI assistance. All records passing title/abstract screening were assessed at full text against the eligibility criteria, with exclusion reasons documented for each excluded study.</p>
</section>
<section id="data-extraction" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="data-extraction"><span class="header-section-number">2.4</span> Data Extraction</h2>
<p>Data were extracted using a standardized form capturing: study identifiers, design (including randomization, sample size, follow-up, analysis approach), population characteristics (perinatal stage, age, baseline severity, setting), intervention details (type, deliverer, format, dose, training, supervision), comparator, primary outcome (scale, timepoints, effect estimates with confidence intervals), and secondary outcomes. Full-text data extraction was completed for two studies with open-access publications available via Europe PMC; the remaining five studies were extracted from published abstracts.</p>
</section>
<section id="risk-of-bias-assessment" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="risk-of-bias-assessment"><span class="header-section-number">2.5</span> Risk of Bias Assessment</h2>
<p>Risk of bias was assessed using the Cochrane Risk of Bias 2 (RoB 2) tool <span class="citation" data-cites="sterne2019rob2">(<a href="#ref-sterne2019rob2" role="doc-biblioref">Sterne et al., 2019</a>)</span> across five domains: randomization process, deviations from intended interventions, missing outcome data, measurement of the outcome, and selection of the reported result. Each domain was rated as low risk, some concerns, or high risk, with an overall judgment for each study. Two studies were reassessed after full-text verification.</p>
</section>
<section id="data-synthesis" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="data-synthesis"><span class="header-section-number">2.6</span> Data Synthesis</h2>
<p>A narrative synthesis was planned as the primary synthesis method, organized by intervention type, population characteristics, and outcomes. A random-effects meta-analysis using standardized mean differences (Hedges’ g) was pre-specified but subject to a feasibility assessment based on data availability and heterogeneity.</p>
<p>The certainty of evidence was assessed using the GRADE framework <span class="citation" data-cites="guyatt2011grade">(<a href="#ref-guyatt2011grade" role="doc-biblioref">Guyatt et al., 2008</a>)</span> across five domains: risk of bias, inconsistency, indirectness, imprecision, and publication bias.</p>
</section>
<section id="use-of-research-workflow-assistant-rwa" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="use-of-research-workflow-assistant-rwa"><span class="header-section-number">2.7</span> Use of Research Workflow Assistant (RWA)</h2>
<p>Research Workflow Assistant (RWA) <span class="citation" data-cites="vanzyl2026rwa">(<a href="#ref-vanzyl2026rwa" role="doc-biblioref">Zyl, 2026</a>)</span>, accessed through GitHub Copilot in VS Code, was used to assist with: literature search execution across databases, record deduplication, presentation of records for screening, data extraction form design, abstract-based data extraction, risk of bias assessment scaffolding, PRISMA flow tracking, and manuscript drafting. As this is a sample project demonstrating tool functionality, no independent human verification of AI-assisted outputs was performed. Outputs may contain errors.</p>
</section>
</section>
<section id="results" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Results</h1>
<section id="study-selection-1" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="study-selection-1"><span class="header-section-number">3.1</span> Study Selection</h2>
<p>Database searches yielded 265,416 records: PubMed (n = 59), OpenAlex (n = 1,442), Semantic Scholar (n = 162), Europe PMC (n = 0, API issue), and CrossRef (n = 263,753). After retrieving the top-ranked records from each database (n = 200) and removing 15 duplicates by DOI and PMID matching, 185 unique records underwent title and abstract screening. All 185 advanced to full-text assessment. Of the 46 records available for full-text screening, 39 were excluded: wrong design — systematic review, meta-analysis, or scoping review (n = 9); protocol without results (n = 12); wrong design — non-RCT or qualitative (n = 7); wrong outcome (n = 6); high-income country setting (n = 3); wrong population (n = 1); unable to retrieve (n = 1). Seven studies met all inclusion criteria and were included in the qualitative synthesis (<a href="#fig-prisma" class="quarto-xref">Figure&nbsp;1</a>).</p>
<div id="fig-prisma" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-prisma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<p><strong>PRISMA 2020 Flow Diagram</strong></p>
<pre><code>Records identified from databases (n = 265,416)
  PubMed: 59 | OpenAlex: 1,442 | Semantic Scholar: 162 | CrossRef: 263,753
                          |
            Top records retrieved (n = 200)
                          |
            Duplicates removed (n = 15)
                          |
         Records screened at title/abstract (n = 185)
                          |
            Records excluded (n = 0)
                          |
        Full-text records assessed (n = 46)
              |                        |
     Excluded (n = 39)          Included (n = 7)
       Wrong design - SR/MA (9)        |
       Protocol only (12)        Qualitative synthesis (n = 7)
       Wrong design - non-RCT (7)     |
       Wrong outcome (6)         Quantitative synthesis (n = 0)
       HIC setting (3)            (meta-analysis not feasible)
       Wrong population (1)
       Unable to retrieve (1)</code></pre>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-prisma-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: PRISMA 2020 flow diagram of study selection.
</figcaption>
</figure>
</div>
</section>
<section id="study-characteristics" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="study-characteristics"><span class="header-section-number">3.2</span> Study Characteristics</h2>
<p><a href="#tbl-characteristics" class="quarto-xref">Table&nbsp;1</a> summarizes the seven included studies. Five were cluster-RCTs, one was an individual RCT, and one was a pilot RCT. Studies were conducted in six countries: Bangladesh (n = 1), China (n = 1), India and Pakistan pooled (n = 1), Pakistan (n = 1), and South Africa (n = 3). Four studies were conducted in upper-middle-income countries (UMIC) and three in lower-middle-income countries (LMIC). No studies from low-income countries met inclusion criteria. Total sample sizes ranged from 72 to 850, with approximately 4,274 participants randomized across all studies and 3,392 analyzed. Follow-up ranged from immediate postpartum to 8 years.</p>
<div id="tbl-characteristics" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-characteristics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Characteristics of included studies. <sup>a</sup>Full-text verified; remaining studies extracted from abstracts. NR = not reported; UMIC = upper-middle-income country; LMIC = lower-middle-income country.
</figcaption>
<div aria-describedby="tbl-characteristics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Study</th>
<th>Country (Income)</th>
<th>Design</th>
<th>N randomized</th>
<th>N analyzed</th>
<th>Perinatal stage</th>
<th>Intervention</th>
<th>Scale</th>
<th>Key finding</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="citation" data-cites="wang2025">Wang et al. (<a href="#ref-wang2025" role="doc-biblioref">2025</a>)</span><sup>a</sup></td>
<td>China (UMIC)</td>
<td>Cluster RCT</td>
<td>592</td>
<td>527</td>
<td>Antenatal</td>
<td>Home visiting</td>
<td>DASS-21</td>
<td>Null overall</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="hossain2024">Hossain et al. (<a href="#ref-hossain2024" role="doc-biblioref">2024</a>)</span><sup>a</sup></td>
<td>Bangladesh (LMIC)</td>
<td>Cluster RCT</td>
<td>587</td>
<td>547</td>
<td>Postnatal</td>
<td>Psychoeducation + cash</td>
<td>SRQ-20</td>
<td>d = −0.20, p &lt; .001</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="rotheramborus2023">Rotheram-Borus et al. (<a href="#ref-rotheramborus2023" role="doc-biblioref">2023</a>)</span></td>
<td>South Africa (UMIC)</td>
<td>Cluster RCT</td>
<td>NR</td>
<td>NR</td>
<td>Both</td>
<td>Home visiting (Philani)</td>
<td>NR (likely EPDS)</td>
<td>Gains dissipated by 5y</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="rossouw2021">Rossouw et al. (<a href="#ref-rossouw2021" role="doc-biblioref">2021</a>)</span></td>
<td>South Africa (UMIC)</td>
<td>Pilot RCT</td>
<td>72</td>
<td>72</td>
<td>Both</td>
<td>Psychosocial + incentive</td>
<td>Unnamed (1–8)</td>
<td>0.928-pt reduction</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="husain2021">Husain et al. (<a href="#ref-husain2021" role="doc-biblioref">2021</a>)</span></td>
<td>Pakistan (LMIC)</td>
<td>Cluster RCT</td>
<td>774</td>
<td>774</td>
<td>Postnatal</td>
<td>Integrated parenting (LTP+)</td>
<td>EPDS</td>
<td>ES = −7.2 (3 mo)</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="vanobberghen2020">Vanobberghen et al. (<a href="#ref-vanobberghen2020" role="doc-biblioref">2020</a>)</span></td>
<td>India &amp; Pakistan (LMIC)</td>
<td>Pooled 2 RCTs</td>
<td>850</td>
<td>704</td>
<td>Both</td>
<td>CBT-based (THP)</td>
<td>PHQ-9</td>
<td>aOR 1.35 remission</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="lund2020">Lund et al. (<a href="#ref-lund2020" role="doc-biblioref">2020</a>)</span></td>
<td>South Africa (UMIC)</td>
<td>Individual RCT</td>
<td>425</td>
<td>384</td>
<td>Both</td>
<td>Structured psychological</td>
<td>HDRS/EPDS</td>
<td>Null finding</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Three studies enrolled only women with clinically significant depression at baseline <span class="citation" data-cites="husain2021 vanobberghen2020 lund2020">(<a href="#ref-husain2021" role="doc-biblioref">Husain et al., 2021</a>, EPDS-selected; <a href="#ref-vanobberghen2020" role="doc-biblioref">Vanobberghen et al., 2020, pp. PHQ–9</a> ≥ 10; <a href="#ref-lund2020" role="doc-biblioref">Lund et al., 2020</a>, EPDS ≥ 13)</span>, while the remaining four enrolled women regardless of depression status.</p>
</section>
<section id="interventions" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="interventions"><span class="header-section-number">3.3</span> Interventions</h2>
<p>Interventions were heterogeneous in type, dose, and delivery model. They included CBT-based therapy <span class="citation" data-cites="vanobberghen2020">(<a href="#ref-vanobberghen2020" role="doc-biblioref">Vanobberghen et al., 2020</a>, Thinking Healthy Programme)</span>, structured psychological treatment <span class="citation" data-cites="lund2020">(<a href="#ref-lund2020" role="doc-biblioref">Lund et al., 2020, p. 6</a> sessions)</span>, integrated parenting and mental health programs <span class="citation" data-cites="husain2021 hossain2024">(<a href="#ref-husain2021" role="doc-biblioref">Husain et al., 2021</a>, Learning Through Play Plus; <a href="#ref-hossain2024" role="doc-biblioref">Hossain et al., 2024</a>, parenting + nutrition + cash)</span>, psychosocial home visiting <span class="citation" data-cites="wang2025 rotheramborus2023">(<a href="#ref-rotheramborus2023" role="doc-biblioref">Rotheram-Borus et al., 2023</a>, Philani Intervention Program; <a href="#ref-wang2025" role="doc-biblioref">Wang et al., 2025</a>)</span>, and psychosocial support with incentive <span class="citation" data-cites="rossouw2021">(<a href="#ref-rossouw2021" role="doc-biblioref">Rossouw et al., 2021</a>, Thula Baba Box)</span>. All interventions used individual delivery; no group-based interventions were identified.</p>
<p>Session dose ranged from 6 planned sessions <span class="citation" data-cites="lund2020">(<a href="#ref-lund2020" role="doc-biblioref">Lund et al., 2020</a>)</span> to approximately 26 fortnightly sessions over 12 months <span class="citation" data-cites="hossain2024">(<a href="#ref-hossain2024" role="doc-biblioref">Hossain et al., 2024</a>)</span>. <span class="citation" data-cites="wang2025">Wang et al. (<a href="#ref-wang2025" role="doc-biblioref">2025</a>)</span> had monthly visits but achieved only 65% compliance. CHW training ranged from 5 days <span class="citation" data-cites="wang2025">(<a href="#ref-wang2025" role="doc-biblioref">Wang et al., 2025</a>)</span> to 10 days <span class="citation" data-cites="hossain2024">(<a href="#ref-hossain2024" role="doc-biblioref">Hossain et al., 2024</a>)</span>; training duration was not reported for five studies.</p>
</section>
<section id="outcome-measures" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="outcome-measures"><span class="header-section-number">3.4</span> Outcome Measures</h2>
<p>Six different validated instruments were used across the seven studies: DASS-21 <span class="citation" data-cites="wang2025">(<a href="#ref-wang2025" role="doc-biblioref">Wang et al., 2025</a>)</span>, SRQ-20 <span class="citation" data-cites="hossain2024">(<a href="#ref-hossain2024" role="doc-biblioref">Hossain et al., 2024</a>)</span>, EPDS <span class="citation" data-cites="husain2021">(<a href="#ref-husain2021" role="doc-biblioref">Husain et al., 2021</a>)</span>, PHQ-9 <span class="citation" data-cites="vanobberghen2020">(<a href="#ref-vanobberghen2020" role="doc-biblioref">Vanobberghen et al., 2020</a>)</span>, HDRS <span class="citation" data-cites="lund2020">(<a href="#ref-lund2020" role="doc-biblioref">Lund et al., 2020</a>, primary)</span> with EPDS as secondary, and an unnamed 1–8 scale <span class="citation" data-cites="rossouw2021">(<a href="#ref-rossouw2021" role="doc-biblioref">Rossouw et al., 2021</a>)</span>. <span class="citation" data-cites="rotheramborus2023">Rotheram-Borus et al. (<a href="#ref-rotheramborus2023" role="doc-biblioref">2023</a>)</span> did not name the depression measure but prior publications from the same trial report the EPDS. Only one study <span class="citation" data-cites="lund2020">(<a href="#ref-lund2020" role="doc-biblioref">Lund et al., 2020</a>)</span> used a clinician-rated instrument; all others relied on self-report measures.</p>
</section>
<section id="effectiveness" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="effectiveness"><span class="header-section-number">3.5</span> Effectiveness</h2>
<section id="studies-reporting-significant-benefits" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="studies-reporting-significant-benefits"><span class="header-section-number">3.5.1</span> Studies Reporting Significant Benefits</h3>
<p>Three studies, all conducted in LMICs, found statistically significant reductions in depression symptoms.</p>
<p><span class="citation" data-cites="husain2021">Husain et al. (<a href="#ref-husain2021" role="doc-biblioref">2021</a>)</span> evaluated Learning Through Play Plus (LTP+) delivered by lay health workers to 774 depressed mothers (EPDS-selected) across 120 villages in Pakistan. Depression scores decreased by a mean difference of −7.2 EPDS points at 3 months (95% CI: −8.2 to −6.1) and −4.6 points at 6 months (95% CI: −5.9 to −3.4), representing a very large clinical effect with intervention group means falling below the clinical threshold.</p>
<p><span class="citation" data-cites="vanobberghen2020">Vanobberghen et al. (<a href="#ref-vanobberghen2020" role="doc-biblioref">2020</a>)</span> pooled individual participant data from two RCTs of peer-delivered Thinking Healthy Programme (THP) in India and Pakistan (n = 850 randomized, 704 analyzed). Among women with PHQ-9 ≥ 10 at baseline, the intervention produced an adjusted mean difference of −0.78 (95% CI: −1.47 to −0.09) and an adjusted odds ratio for remission (PHQ-9 &lt; 5) of 1.35 (95% CI: 1.02 to 1.78).</p>
<p><span class="citation" data-cites="hossain2024">Hossain et al. (<a href="#ref-hossain2024" role="doc-biblioref">2024</a>)</span> evaluated a psychoeducation plus unconditional cash transfer intervention in urban Bangladesh (n = 587 randomized, 547 analyzed). Depression scores on the SRQ-20 decreased significantly (β = −1.53, 95% CI: −2.28 to −0.80, p &lt; .001; Cohen’s d = −0.20). All four quality-of-life domains also improved significantly. Depression was a secondary outcome; the trial was primarily designed to assess child development.</p>
</section>
<section id="studies-reporting-null-or-transient-effects" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="studies-reporting-null-or-transient-effects"><span class="header-section-number">3.5.2</span> Studies Reporting Null or Transient Effects</h3>
<p>Four studies, all conducted in UMICs, found no significant or sustained intervention effect.</p>
<p><span class="citation" data-cites="wang2025">Wang et al. (<a href="#ref-wang2025" role="doc-biblioref">2025</a>)</span> evaluated a community home-visiting program for pregnant women across 79 townships in rural China (n = 592 randomized, 527 analyzed). No significant effects were found on DASS-21 depression (β = 0.51, NS), anxiety (β = 0.40, NS), or stress (β = 0.27, NS). Exploratory moderator analyses suggested benefits among women whose husbands accompanied antenatal visits (p &lt; .10). Low compliance (65%) may have attenuated effects.</p>
<p><span class="citation" data-cites="lund2020">Lund et al. (<a href="#ref-lund2020" role="doc-biblioref">2020</a>)</span> conducted the only double-blind trial in this review, evaluating six sessions of CHW-delivered psychological treatment for depressed pregnant women in peri-urban South Africa (n = 425 randomized, 384 analyzed). No significant difference in HDRS response was found at 3 months postpartum.</p>
<p><span class="citation" data-cites="rotheramborus2023">Rotheram-Borus et al. (<a href="#ref-rotheramborus2023" role="doc-biblioref">2023</a>)</span> reported 8-year follow-up of the Philani home visiting program in South Africa. Initial depression reductions observed at 3 years had dissipated by 5 and 8 years, with depression prevalence declining to 5.5% in both groups.</p>
<p><span class="citation" data-cites="rossouw2021">Rossouw et al. (<a href="#ref-rossouw2021" role="doc-biblioref">2021</a>)</span> was a pilot RCT (n = 72) of the Thula Baba Box plus CHW program in South Africa. A 0.928-point reduction on an unnamed 1–8 depression scale was reported without confidence intervals or significance testing.</p>
</section>
</section>
<section id="risk-of-bias" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="risk-of-bias"><span class="header-section-number">3.6</span> Risk of Bias</h2>
<p><a href="#tbl-rob2" class="quarto-xref">Table&nbsp;2</a> presents the risk of bias assessments. One study was rated low risk of bias <span class="citation" data-cites="lund2020">(<a href="#ref-lund2020" role="doc-biblioref">Lund et al., 2020</a>)</span>, five at some concerns, and one at high risk <span class="citation" data-cites="rossouw2021">(<a href="#ref-rossouw2021" role="doc-biblioref">Rossouw et al., 2021</a>)</span>.</p>
<div id="tbl-rob2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rob2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Risk of bias assessments using Cochrane RoB 2.
</figcaption>
<div aria-describedby="tbl-rob2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Study</th>
<th>Domain 1: Randomization</th>
<th>Domain 2: Deviations</th>
<th>Domain 3: Missing data</th>
<th>Domain 4: Measurement</th>
<th>Domain 5: Reporting</th>
<th>Overall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="citation" data-cites="wang2025">Wang et al. (<a href="#ref-wang2025" role="doc-biblioref">2025</a>)</span></td>
<td>Some concerns</td>
<td>Some concerns</td>
<td>Low</td>
<td>Some concerns</td>
<td>Some concerns</td>
<td>Some concerns</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="hossain2024">Hossain et al. (<a href="#ref-hossain2024" role="doc-biblioref">2024</a>)</span></td>
<td>Some concerns</td>
<td>Some concerns</td>
<td>Low</td>
<td>Some concerns</td>
<td>Low</td>
<td>Some concerns</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="rotheramborus2023">Rotheram-Borus et al. (<a href="#ref-rotheramborus2023" role="doc-biblioref">2023</a>)</span></td>
<td>Some concerns</td>
<td>Some concerns</td>
<td>No information</td>
<td>Some concerns</td>
<td>No information</td>
<td>Some concerns</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="rossouw2021">Rossouw et al. (<a href="#ref-rossouw2021" role="doc-biblioref">2021</a>)</span></td>
<td>High</td>
<td>Some concerns</td>
<td>No information</td>
<td>High</td>
<td>No information</td>
<td>High</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="husain2021">Husain et al. (<a href="#ref-husain2021" role="doc-biblioref">2021</a>)</span></td>
<td>Low</td>
<td>Some concerns</td>
<td>No information</td>
<td>Some concerns</td>
<td>No information</td>
<td>Some concerns</td>
</tr>
<tr class="even">
<td><span class="citation" data-cites="vanobberghen2020">Vanobberghen et al. (<a href="#ref-vanobberghen2020" role="doc-biblioref">2020</a>)</span></td>
<td>Low</td>
<td>Some concerns</td>
<td>Some concerns</td>
<td>Some concerns</td>
<td>Probably yes</td>
<td>Some concerns</td>
</tr>
<tr class="odd">
<td><span class="citation" data-cites="lund2020">Lund et al. (<a href="#ref-lund2020" role="doc-biblioref">2020</a>)</span></td>
<td>Low</td>
<td>Low</td>
<td>Low</td>
<td>Low</td>
<td>Low</td>
<td>Low</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The most common concerns were related to measurement of the outcome (Domain 4), reflecting the open-label design of most studies combined with self-report outcome measures. <span class="citation" data-cites="lund2020">Lund et al. (<a href="#ref-lund2020" role="doc-biblioref">2020</a>)</span> was the only study to achieve low risk across all domains, owing to its double-blind design and use of clinician-rated HDRS as the primary outcome.</p>
<p>A notable pattern emerged: the lowest-risk-of-bias study <span class="citation" data-cites="lund2020">(<a href="#ref-lund2020" role="doc-biblioref">Lund et al., 2020</a>)</span> found null results, while the highest-risk-of-bias study <span class="citation" data-cites="rossouw2021">(<a href="#ref-rossouw2021" role="doc-biblioref">Rossouw et al., 2021</a>)</span> reported positive results. Among the five studies at some concerns, results were mixed.</p>
</section>
<section id="meta-analysis-feasibility" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="meta-analysis-feasibility"><span class="header-section-number">3.7</span> Meta-Analysis Feasibility</h2>
<p>The pre-specified random-effects meta-analysis was determined to be infeasible for three principal reasons. First, only three of seven studies <span class="citation" data-cites="hossain2024 husain2021 vanobberghen2020">(<a href="#ref-hossain2024" role="doc-biblioref">Hossain et al., 2024</a>; <a href="#ref-husain2021" role="doc-biblioref">Husain et al., 2021</a>; <a href="#ref-vanobberghen2020" role="doc-biblioref">Vanobberghen et al., 2020</a>)</span> reported effect estimates from which standardized mean differences could potentially be computed; the remaining four either reported only regression coefficients without group means and standard deviations <span class="citation" data-cites="wang2025">(<a href="#ref-wang2025" role="doc-biblioref">Wang et al., 2025</a>)</span>, Bayesian posteriors without point estimates <span class="citation" data-cites="rotheramborus2023">(<a href="#ref-rotheramborus2023" role="doc-biblioref">Rotheram-Borus et al., 2023</a>)</span>, unstandardized differences without variance measures <span class="citation" data-cites="rossouw2021">(<a href="#ref-rossouw2021" role="doc-biblioref">Rossouw et al., 2021</a>)</span>, or binary response rates without continuous estimates <span class="citation" data-cites="lund2020">(<a href="#ref-lund2020" role="doc-biblioref">Lund et al., 2020</a>)</span>. Second, six different outcome instruments were used, and several — SRQ-20, DASS-21, and the unnamed 1–8 scale — measure related but distinct constructs, limiting the interpretability of pooled standardized differences. Third, studies varied substantially in population (treatment vs.&nbsp;prevention samples), intervention type, comparator, follow-up duration, and design, producing clinical and methodological heterogeneity that would undermine the validity of a pooled estimate even if effect sizes were available. With only seven studies, planned subgroup and sensitivity analyses would be underpowered.</p>
</section>
<section id="certainty-of-evidence-grade" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="certainty-of-evidence-grade"><span class="header-section-number">3.8</span> Certainty of Evidence (GRADE)</h2>
<p>The overall certainty of evidence was rated <strong>very low</strong> (<a href="#tbl-grade" class="quarto-xref">Table&nbsp;3</a>). Starting from high (randomized trials), evidence was downgraded one level each for risk of bias (mixed risk profiles; the lowest-risk study found null results), inconsistency (highly variable direction and magnitude of effects across studies), and imprecision (wide confidence intervals, incomplete numeric reporting, small samples in some studies). Publication bias was not formally assessable with fewer than 10 studies.</p>
<div id="tbl-grade" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-grade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: GRADE evidence certainty assessment.
</figcaption>
<div aria-describedby="tbl-grade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 40%">
<col style="width: 25%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>GRADE domain</th>
<th>Rating</th>
<th>Rationale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Starting level</td>
<td>High</td>
<td>All RCTs</td>
</tr>
<tr class="even">
<td>Risk of bias</td>
<td>−1</td>
<td>Mixed RoB; lowest-RoB study null; most studies abstract-level assessment</td>
</tr>
<tr class="odd">
<td>Inconsistency</td>
<td>−1</td>
<td>Direction varies (3 positive, 3 null, 1 unclear); magnitude ranges from d = −0.20 to ES = −7.2</td>
</tr>
<tr class="even">
<td>Indirectness</td>
<td>0</td>
<td>Studies directly address PICO</td>
</tr>
<tr class="odd">
<td>Imprecision</td>
<td>−1</td>
<td>Wide CIs; insufficient data from most studies; small sample in pilot study</td>
</tr>
<tr class="even">
<td>Publication bias</td>
<td>Not assessable</td>
<td>&lt; 10 studies</td>
</tr>
<tr class="odd">
<td><strong>Overall certainty</strong></td>
<td><strong>Very low</strong></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="discussion" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Discussion</h1>
<section id="summary-of-evidence" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="summary-of-evidence"><span class="header-section-number">4.1</span> Summary of Evidence</h2>
<p>This systematic review identified seven RCTs evaluating CHW-delivered psychosocial and psychological interventions for perinatal women across six LMICs. The evidence revealed a mixed and heterogeneous picture: three studies in lower-middle-income countries found significant depression reductions, while all four studies in upper-middle-income countries found null or transient effects. Meta-analysis was not feasible due to heterogeneity in outcome measures, insufficient reporting of effect-size components, and clinical diversity across studies. The certainty of evidence was rated very low using the GRADE framework.</p>
</section>
<section id="patterns-in-effectiveness" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="patterns-in-effectiveness"><span class="header-section-number">4.2</span> Patterns in Effectiveness</h2>
<p>Several patterns merit discussion. First, the apparent difference in effectiveness between LMIC and UMIC settings may reflect genuinely greater impact where formal mental health services are scarce — consistent with the broader task-shifting literature suggesting that CHW interventions are most effective where they fill an unmet need. However, this pattern is confounded by differences in population selection (two of three LMIC studies enrolled clinically depressed women) and intervention type, limiting causal interpretation.</p>
<p>Second, interventions integrating mental health support with parenting education, nutrition, or economic components <span class="citation" data-cites="husain2021 hossain2024">(<a href="#ref-hossain2024" role="doc-biblioref">Hossain et al., 2024</a>; <a href="#ref-husain2021" role="doc-biblioref">Husain et al., 2021</a>)</span> appeared more effective than single-focus psychosocial or structured psychological interventions. This aligns with evidence from the broader perinatal health literature suggesting that addressing multiple determinants simultaneously may enhance engagement and effectiveness. However, the small number of studies precludes definitive conclusions.</p>
<p>Third, the association between lower risk of bias and null findings is concerning and may indicate that positive effects reported in higher-risk studies are partially attributable to methodological limitations — particularly the combination of unblinded interventions with self-report outcomes, which is susceptible to expectancy and social desirability bias.</p>
</section>
<section id="strengths-and-limitations" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="strengths-and-limitations"><span class="header-section-number">4.3</span> Strengths and Limitations</h2>
<p>This review has several strengths: a comprehensive search across five databases, systematic screening with documented exclusion reasons, use of the Cochrane RoB 2 tool for risk of bias assessment, GRADE evidence certainty assessment, and transparent documentation of AI-assisted processes.</p>
<p>Key limitations include: (1) reliance on abstract-level data for five of seven studies, as full text was not openly accessible for most included studies — this may result in incomplete or imprecise data extraction; (2) search strategy limitations, as Europe PMC returned no results due to an API issue, and the high-volume CrossRef results suggest the query may have been overly broad for that database; (3) single-reviewer screening and extraction, which increases the risk of errors; (4) inability to perform meta-analysis, limiting the strength of quantitative conclusions; and (5) the small number of included studies (n = 7), which limits subgroup analysis and formal assessment of publication bias.</p>
</section>
<section id="comparison-with-previous-reviews" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="comparison-with-previous-reviews"><span class="header-section-number">4.4</span> Comparison with Previous Reviews</h2>
<p>The findings are broadly consistent with prior systematic reviews examining task-shifting mental health interventions in LMICs. The Thinking Healthy Programme <span class="citation" data-cites="vanobberghen2020">(represented in this review by <a href="#ref-vanobberghen2020" role="doc-biblioref">Vanobberghen et al., 2020</a>)</span> has been recognized by the WHO as an evidence-based intervention for perinatal depression. The null findings in UMIC settings, particularly the high-quality <span class="citation" data-cites="lund2020">Lund et al. (<a href="#ref-lund2020" role="doc-biblioref">2020</a>)</span> trial, add to a growing recognition that CHW mental health interventions do not universally improve outcomes and that context, implementation quality, and study design significantly influence results.</p>
</section>
<section id="implications-for-practice" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="implications-for-practice"><span class="header-section-number">4.5</span> Implications for Practice</h2>
<p>Given the very low certainty of evidence, practice recommendations must be tentative. Integration of mental health components into existing CHW parenting or nutrition programs appears promising in lower-middle-income settings. Screening for depression and targeting interventions to symptomatic women may improve effectiveness over universal prevention approaches. Adequate CHW training (at least 10 days) and compliance monitoring appear to be important implementation factors.</p>
</section>
<section id="implications-for-research" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="implications-for-research"><span class="header-section-number">4.6</span> Implications for Research</h2>
<p>Future trials should prioritize: (1) reporting of group means, standard deviations, and standardized effect sizes to enable meta-analysis; (2) use of common validated outcome measures such as the EPDS for perinatal populations; (3) blinded outcome assessment where feasible; (4) long-term follow-up beyond 12 months; (5) inclusion of low-income country settings; and (6) designs with maternal mental health as the primary outcome rather than a secondary endpoint of child development trials.</p>
</section>
</section>
<section id="conclusions" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Conclusions</h1>
<p>This systematic review found very low certainty evidence that CHW-delivered interventions may reduce depression symptoms among perinatal women in LMICs. Effectiveness appeared more consistent in lower-middle-income settings and with integrated intervention approaches targeting clinically depressed women. However, the evidence is limited by substantial heterogeneity in interventions, outcome measures, and study quality. The inability to conduct meta-analysis due to inconsistent effect-size reporting underscores the need for standardized outcome reporting in future trials. High-quality trials in low-income countries, with long-term follow-up and standardized outcome measures, are urgently needed to strengthen this evidence base.</p>
</section>
<section id="acknowledgments-and-ai-disclosure" class="level1 unnumbered">
<h1 class="unnumbered">Acknowledgments and AI Disclosure</h1>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Disclaimer
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is a sample project created solely to demonstrate the functionality of the Research Workflow Assistant (RWA). No person claims authorship. None of the content has been independently verified and may contain errors. This document should not be cited, used for clinical decision-making, or treated as a valid systematic review.</p>
</div>
</div>
<p><strong>AI disclosure (per ICMJE Section II.A.4):</strong> This sample manuscript was generated entirely by Research Workflow Assistant (RWA) <span class="citation" data-cites="vanzyl2026rwa">(<a href="#ref-vanzyl2026rwa" role="doc-biblioref">Zyl, 2026</a>)</span>, accessed through GitHub Copilot in VS Code, to demonstrate tool capabilities including: literature search execution across databases, record deduplication, screening presentation, data extraction, risk of bias assessment scaffolding, PRISMA flow tracking, synthesis drafting, and manuscript preparation. No author reviewed, verified, or approved the outputs. A detailed log of AI contributions is maintained in the project repository.</p>
<p><strong>Data source attribution:</strong> Literature search results were supplemented using the Semantic Scholar Open Data Platform <span class="citation" data-cites="kinney2023">(<a href="#ref-kinney2023" role="doc-biblioref">Kinney et al., 2023</a>)</span>, which provides data under a CC BY-NC license.</p>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-fisher2012" class="csl-entry" role="listitem">
Fisher, J., Cabral de Mello, M., Patel, V., Rahman, A., Tran, T., Holton, S., &amp; Holmes, W. (2012). Prevalence and determinants of common perinatal mental disorders in women in low- and lower-middle-income countries: A systematic review. <em>Bulletin of the World Health Organization</em>, <em>90</em>(2), 139–149. <a href="https://doi.org/10.2471/BLT.11.091850">https://doi.org/10.2471/BLT.11.091850</a>
</div>
<div id="ref-guyatt2011grade" class="csl-entry" role="listitem">
Guyatt, G. H., Oxman, A. D., Vist, G. E., Kunz, R., Falck-Ytter, Y., Alonso-Coello, P., &amp; Schünemann, H. J. (2008). <span>GRADE</span>: An emerging consensus on rating quality of evidence and strength of recommendations. <em>BMJ</em>, <em>336</em>(7650), 924–926. <a href="https://doi.org/10.1136/bmj.39489.470347.AD">https://doi.org/10.1136/bmj.39489.470347.AD</a>
</div>
<div id="ref-hossain2024" class="csl-entry" role="listitem">
Hossain, S. J., Tofail, F., Rahman, A., Fisher, J., Hamadani, J. D., &amp; Rahman, S. M. (2024). Parenting with nutrition education and unconditional cash reduce maternal depressive symptoms and improve quality of life: Findings from a cluster randomised controlled trial in urban <span>Bangladesh</span>. <em>Global Health Action</em>, <em>17</em>(1). <a href="https://doi.org/10.1080/16549716.2024.2426784">https://doi.org/10.1080/16549716.2024.2426784</a>
</div>
<div id="ref-husain2021" class="csl-entry" role="listitem">
Husain, N., Kiran, T., Fatima, B., Chaudhry, I. B., Husain, M., Shah, S., Bassett, P., Cohen, N., Jafri, F., Naeem, S., Zadeh, Z., Roberts, C., Rahman, A., Naeem, F., Husain, M., &amp; Chaudhry, N. (2021). An integrated parenting intervention for maternal depression and child development in a low-resource setting: Cluster randomized controlled trial. <em>Depression and Anxiety</em>, <em>38</em>(9), 925–939. <a href="https://doi.org/10.1002/da.23169">https://doi.org/10.1002/da.23169</a>
</div>
<div id="ref-kinney2023" class="csl-entry" role="listitem">
Kinney, R., Anastasiades, C., Authur, R., Beltagy, I., Bragg, J., Buber, A., Callaham, J., Cash, D., Castillo, D., Chen, Z., Clark, R., Cohn, D., Cohen, S., Deardorff, K., Degennaro, T., Doug, F., Fisher, M., Feldman, A., Freitag, M., et al.others. (2023). The <span>Semantic Scholar Open Data Platform</span>. <em>ArXiv</em>, <em>abs/2301.10140</em>. <a href="https://doi.org/10.48550/arXiv.2301.10140">https://doi.org/10.48550/arXiv.2301.10140</a>
</div>
<div id="ref-lund2020" class="csl-entry" role="listitem">
Lund, C., Schneider, M., Garman, E. C., Davies, T., Munodawafa, M., Honikman, S., Bhana, A., Bass, J., Bolton, P., Dewey, M., Joska, J., Kagee, A., Myer, L., Petersen, I., Prince, M., Stein, D. J., Tabana, H., Thornicroft, G., Tomlinson, M., … Susser, E. (2020). Task-sharing of psychological treatment for antenatal depression in <span>Khayelitsha</span>, <span>South Africa</span>: Effects on antenatal and postnatal outcomes in an individual randomised controlled trial. <em>Behaviour Research and Therapy</em>, <em>130</em>, 103466. <a href="https://doi.org/10.1016/j.brat.2019.103466">https://doi.org/10.1016/j.brat.2019.103466</a>
</div>
<div id="ref-page2021prisma" class="csl-entry" role="listitem">
Page, M. J., McKenzie, J. E., Bossuyt, P. M., Boutron, I., Hoffmann, T. C., Mulrow, C. D., Shamseer, L., Tetzlaff, J. M., Akl, E. A., Brennan, S. E., Chou, R., Glanville, J., Grimshaw, J. M., Hróbjartsson, A., Lalu, M. M., Li, T., Loder, E. W., Mayo-Wilson, E., McDonald, S., … Moher, D. (2021). The <span>PRISMA</span> 2020 statement: An updated guideline for reporting systematic reviews. <em>BMJ</em>, <em>372</em>, n71. <a href="https://doi.org/10.1136/bmj.n71">https://doi.org/10.1136/bmj.n71</a>
</div>
<div id="ref-rahman2008" class="csl-entry" role="listitem">
Rahman, A., Malik, A., Sikander, S., Roberts, C., &amp; Creed, F. (2008). Cognitive behaviour therapy-based intervention by community health workers for mothers with depression and their infants in rural <span>Pakistan</span>: A cluster-randomised controlled trial. <em>The Lancet</em>, <em>372</em>(9642), 902–909. <a href="https://doi.org/10.1016/S0140-6736(08)61400-2">https://doi.org/10.1016/S0140-6736(08)61400-2</a>
</div>
<div id="ref-rossouw2021" class="csl-entry" role="listitem">
Rossouw, L., Burger, R. P., &amp; Burger, R. (2021). Testing an incentive-based and community health worker package intervention to improve maternal health and nutrition outcomes: A pilot randomized controlled trial. <em>Maternal and Child Health Journal</em>, <em>25</em>(12), 1913–1922. <a href="https://doi.org/10.1007/s10995-021-03229-w">https://doi.org/10.1007/s10995-021-03229-w</a>
</div>
<div id="ref-rotheramborus2023" class="csl-entry" role="listitem">
Rotheram-Borus, M. J., Tomlinson, M., Worthman, C. M., Norwood, P., Roux, I. le, &amp; O’Connor, M. J. (2023). Maternal depression, alcohol use, and transient effects of perinatal paraprofessional home visiting in <span>South Africa</span>: Eight-year follow-up of a cluster randomized controlled trial. <em>Social Science &amp; Medicine</em>, <em>324</em>, 115853. <a href="https://doi.org/10.1016/j.socscimed.2023.115853">https://doi.org/10.1016/j.socscimed.2023.115853</a>
</div>
<div id="ref-stein2014" class="csl-entry" role="listitem">
Stein, A., Pearson, R. M., Goodman, S. H., Rapa, E., Rahman, A., McCallum, M., Howard, L. M., &amp; Pariante, C. M. (2014). Effects of perinatal mental disorders on the fetus and child. <em>The Lancet</em>, <em>384</em>(9956), 1800–1819. <a href="https://doi.org/10.1016/S0140-6736(14)61277-0">https://doi.org/10.1016/S0140-6736(14)61277-0</a>
</div>
<div id="ref-sterne2019rob2" class="csl-entry" role="listitem">
Sterne, J. A. C., Savović, J., Page, M. J., Elbers, R. G., Blencowe, N. S., Boutron, I., Cates, C. J., Cheng, H.-Y., Corbett, M. S., Eldridge, S. M., Emberson, J. R., Hernán, M. A., Hopewell, S., Hróbjartsson, A., Junqueira, D. R., Jüni, P., Kirkham, J. J., Lasserson, T., Li, T., … Higgins, J. P. T. (2019). <span>RoB</span> 2: A revised tool for assessing risk of bias in randomised trials. <em>BMJ</em>, <em>366</em>, l4898. <a href="https://doi.org/10.1136/bmj.l4898">https://doi.org/10.1136/bmj.l4898</a>
</div>
<div id="ref-surkan2011" class="csl-entry" role="listitem">
Surkan, P. J., Kennedy, C. E., Hurley, K. M., &amp; Black, M. M. (2011). Maternal depression and early childhood growth in developing countries: Systematic review and meta-analysis. <em>Bulletin of the World Health Organization</em>, <em>89</em>(8), 608–615. <a href="https://doi.org/10.2471/BLT.11.088187">https://doi.org/10.2471/BLT.11.088187</a>
</div>
<div id="ref-vanobberghen2020" class="csl-entry" role="listitem">
Vanobberghen, F., Weiss, H. A., Fuhr, D. C., Sikander, S., Afonso, E., Ahmad, I., Atif, N., Bibi, A., Bibi, T., Bilal, S., De Sa, A., D’souza, E., Joshi, A., Korgaonkar, P., Krishna, R., Lazarus, A., Liaqat, R., Sharif, M., Weobong, B., … Rahman, A. (2020). Effectiveness of the <span>Thinking Healthy Programme</span> for perinatal depression delivered through peers: Pooled analysis of two randomized controlled trials in <span>India</span> and <span>Pakistan</span>. <em>Journal of Affective Disorders</em>, <em>265</em>, 560–568. <a href="https://doi.org/10.1016/j.jad.2019.11.110">https://doi.org/10.1016/j.jad.2019.11.110</a>
</div>
<div id="ref-wang2025" class="csl-entry" role="listitem">
Wang, N., Li, B., Yang, J., Liu, Z., Shi, Y., &amp; Nie, J. (2025). The mental health benefit of a community-based home-visiting program for prenatal women: Evidence from a randomized controlled trial in <span>China</span>. <em>BMC Pregnancy and Childbirth</em>, <em>25</em>(1). <a href="https://doi.org/10.1186/s12884-025-08297-2">https://doi.org/10.1186/s12884-025-08297-2</a>
</div>
<div id="ref-woody2017" class="csl-entry" role="listitem">
Woody, C. A., Ferrari, A. J., Siskind, D. J., Whiteford, H. A., &amp; Harris, M. G. (2017). A systematic review and meta-regression of the prevalence and incidence of perinatal depression. <em>Journal of Affective Disorders</em>, <em>219</em>, 86–92. <a href="https://doi.org/10.1016/j.jad.2017.05.003">https://doi.org/10.1016/j.jad.2017.05.003</a>
</div>
<div id="ref-who2008taskshifting" class="csl-entry" role="listitem">
World Health Organization. (2008). <em>Task shifting: Rational redistribution of tasks among health workforce teams: Global recommendations and guidelines</em>. World Health Organization. <a href="https://www.who.int/publications/i/item/9789241596312">https://www.who.int/publications/i/item/9789241596312</a>
</div>
<div id="ref-who2021atlas" class="csl-entry" role="listitem">
World Health Organization. (2021). <em>Mental health atlas 2020</em>. World Health Organization. <a href="https://www.who.int/publications/i/item/9789240036703">https://www.who.int/publications/i/item/9789240036703</a>
</div>
<div id="ref-vanzyl2026rwa" class="csl-entry" role="listitem">
Zyl, A. van. (2026). <em>Research workflow assistant (RWA)</em> [Computer software]. <a href="https://github.com/andre-inter-collab-llc/research-workflow-assistant">https://github.com/andre-inter-collab-llc/research-workflow-assistant</a>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>